baseURL = "https://wright-development.github.io/"
languageCode = "en-us"
title = "Wright Development"
theme = "amp"
disqusShortname = "https-wright-development-github-io.disqus.com"

[params]
    amp = true
    ampElements = ["amp-form"]
    description = "Developing the Wright way"
    googleanalytics = "UA-61721549-2"
[params.author]
    firstName = "Darrius"
    lastName = "Wright"
    gender = "male"

[social]
  github = "wright-development"
  linkedin = "darrius-wright"

[params.staticman]
  endpoint = "https://api.staticman.net/v2/entry/"
  username = "wright-development"
  repository = "wright-development.github.io"
  branch = "master"
