baseURL = "https://wright-development.github.io/"
languageCode = "en-us"
title = "Wright Development"
theme = "amp"

[params]
    description = "Developing the Wright way"
    googleanalytics = "UA-61721549-2"
[params.author]
    firstName = "Darrius"
    lastName = "Wright"
    gender = "male"

[social]
  github = "wright-development"
  linkedin = "darrius-wright"

[[menu.main]]
    name = "Contact Me"
    identifier = "contact-me"
    url = "/contact-me/"