baseURL = "https://wright-development.github.io/"
languageCode = "en-us"
title = "Wright Development"
theme = "blackburn"
copyright = "Wright Development &copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
    subtitle = "Developing the Wright way"
    googleanalytics = "UA-61721549-2"
    highlightjs = "tomorrow-night-eighties"
    highlightjs_extra_languages = ["yaml", "dockerfile"]
    dateFormat = "02 January 2006"

[params.author]
    firstName = "Darrius"
    lastName = "Wright"
    gender = "male"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Expected.Request"
    weight = 3
    identifier = "expected-request"
    url = "https://wright-development.github.io/Expected.Request/"

[social]
  github = "wright-development"
  linkedin = "darrius-wright"
  twitter = "develop_wright"

[params.staticman]
  endpoint = "https://api.staticman.net/v2/entry/"
  username = "wright-development"
  repository = "wright-development.github.io"
  branch = "master"